spring:
  application:
    name: broker-service
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  
  web:
    resources:
      static-locations: 
        - classpath:/static/
        - classpath:/public/
      cache:
        period: 31536000

ms-server:
  edutrack: https://localhost:8081
  bluefolder: https://localhost:8082

client:
  ssl:
    key-cert-path: /Users/rssillador/Documents/projects/rssrs/certificates/client.crt
    key-path: /Users/rssillador/Documents/projects/rssrs/certificates/client.key
    trust-cert-path: /Users/rssillador/Documents/projects/rssrs/certificates/ca.crt
    key-store: /Users/rssillador/Documents/projects/rssrs/certificates/client-keystore.p12
    key-store-password: secret
    key-password: secret
    key-store-type: PKCS12
    trust-store: /Users/rssillador/Documents/projects/rssrs/certificates/client-truststore.p12
    trust-store-password: secret
    trust-store-type: PKCS12

jwt:
  key: your_super_secure_and_long_enough_jwt_secret_key_123!

file:
  upload:
    path: /Users/rssillador/Documents/projects/rssrs/uploads
    profile-pictures:
      path: ${file.upload.path}/profile-pictures
    documents:
      path: ${file.upload.path}/documents
